### ISSUE TITLE
Supply Makefile.PL and other aspects of CPAN-like distribution

### ISSUE THREAD

**Issue by jkeenan** [MediaMath/catalyst-controller-swagger#2]
To decrease the barriers to entry to potential contributors to this repository, I would encourage you to enable users, once they have downloaded your code, to build and test your module with standard Perl tools, i.e., a Makefile.PL that will enable one to say:

``` bash
perl Makefile.PL
make
make test
```

In other words, you should not implicitly require the use of more advanced, but less widely used, tools such as Dist::Zilla or carton.

Also, please consider reducing your prerequisites for building and testing code.  If, for example, Test::More functions will suffice, then require that rather than Test::Most.

Thank you very much.
Jim Keenan

**Comment by logie17** [comment]
As per our discussion at YAPC, I agree with your suggestion. Please see the following experimental branch: https://github.com/MediaMath/catalyst-controller-swagger/tree/feature/switch-to-makefile. I hope to also have docs updated in this branch shortly too.
